---
registry_public_host: "{{ lookup('env', 'REGISTRY_PUBLIC_HOST') }}"
registry_public_port: "{{ lookup('env', 'REGISTRY_PUBLIC_PORT') }}"
registry_public_url: "{{ registry_public_host }}:{{ registry_public_port }}"

# Development config
# -----------------------------------------------------------------------------
artifactory_username: "{{ lookup('env', 'ARTIFACTORY_USERNAME') | lower }}"
artifactory_token: "{{ lookup('env', 'ARTIFACTORY_TOKEN') }}"
artifactory_auth: "{{ artifactory_username }}:{{ artifactory_token }}"

# Authentication - IBM
# -----------------------------------------------------------------------------
ibm_entitlement_key: "{{ lookup('env', 'IBM_ENTITLEMENT_KEY') }}"
ibm_auth: "cp:{{ ibm_entitlement_key }}"

# Authentication - RedHat
# -----------------------------------------------------------------------------
redhat_connect_username: "{{ lookup('env', 'REDHAT_CONNECT_USERNAME') }}"
redhat_connect_password: "{{ lookup('env', 'REDHAT_CONNECT_PASSWORD') }}"
redhat_connect_auth: "{{ redhat_connect_username }}:{{ redhat_connect_password }}"

# Authentication - Target Registry
# -----------------------------------------------------------------------------
registry_username: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
registry_password: "{{ lookup('env', 'REGISTRY_PASSWORD') }}"
registry_auth: "{{ registry_username }}:{{ registry_password }}"

mirror_mode: "{{ lookup('env', 'MIRROR_MODE') }}"
mirror_working_dir: "{{ lookup('env', 'MIRROR_WORKING_DIR') }}"
manifest_name: "{{ lookup('env', 'MANIFEST_NAME') }}"
manifest_version: "{{ lookup('env', 'MANIFEST_VERSION') }}"
auth_file: "{{ ansible_env.HOME }}/.ibm-mas/auth.json"

mirror_single_arch: "{{ lookup('env', 'MIRROR_SINGLE_ARCH') }}"
